#!/bin/sh
# for template
eval "cut -c2- << x 
$(sed 's/[\$`]/\\&/g;s/{{ \([^ ]*\) }}/${\1}/g;s/^/y/' < /usr/local/openresty/nginx/conf/nginx.conf.template)
x" > /usr/local/openresty/nginx/conf/nginx.conf

/usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
